### ISSUE TITLE
Ajouter Ditto

### ISSUE THREAD

**Issue by thsempai** [joruchan/JYF#1]
Je serais ravi de voir Ditto sur votre Site :D

**Comment by joruchan** [comment]
Bon c'est bien parce que t'es le prof et qu'on est obligées de faire ce que tu dis...!

**Comment by Yun-ux** [comment]
l'image a été soumise à la personne qui fait l'html

**Comment by samuraitea** [comment]
La personne qui fait l'HTML a pris en compte votre requête.

**Comment by joruchan** [comment]
Nous avons ajouté Ditto !
